In [2]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '{:.15f}'.format(x).rstrip('0').rstrip('.'))

import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv(r'data_csv\superstore.csv').dropna(how='all').drop_duplicates(keep='last')
df = df.reset_index(drop=True)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.95999999999998,2,0,41.913600000000002
1,2,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940000000000055,3,0,219.581999999999994
2,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.619999999999999,2,0,6.8714
3,4,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.577499999999986,5,0.45,-383.031000000000006
4,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.367999999999999,2,0.2,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10291,Yes,US-2018-136679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10292,Yes,US-2018-147886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10293,Yes,US-2018-147998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10294,Yes,US-2018-151127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10295,Yes,US-2018-155999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Create a DataFrame for 'Country':

df_country = pd.DataFrame(columns=["country_id", "country"])

# INSERT DATA : COUNTRY
unique_countries = df["Country"].dropna().unique()
df_country = pd.DataFrame({
    "country_id": range(1, len(unique_countries) + 1),
    "country":    unique_countries
})

df_country.head(10)

   country_id        country
0           1  United States

In [4]:
# Create a DataFrame for 'Region':

df_region = pd.DataFrame(columns=["region_id", "region", "country_id"])

#INSERT DATA : REGION
unique_regions = (
    df[["Country", "Region"]]
    .dropna()
    .drop_duplicates()
    .merge(df_country, left_on="Country", right_on="country")
    .rename(columns={"country_id": "country_id"})
    [["Region", "country_id"]]
)
df_region = unique_regions.reset_index(drop=True)
df_region.insert(0, "region_id", range(1, len(df_region) + 1))
df_region = df_region.rename(columns={"Region": "region"})

df_region.head(10)

   region_id   region  country_id
0          1    South           1
1          2     West           1
2          3  Central           1
3          4     East           1

In [5]:
# Create a DataFrame for 'State':

df_state = pd.DataFrame(columns=["state_id", "state", "region_id"])

# INSERT DATA : STATE
unique_states = (
    df[["State", "Region"]]
    .dropna()
    .drop_duplicates()
    .merge(df_region, left_on="Region", right_on="region")
    [["State", "region_id"]]
)
df_state = unique_states.reset_index(drop=True)
df_state.insert(0, "state_id", range(1, len(df_state) + 1))
df_state = df_state.rename(columns={"State": "state"})
 
df_state.head()

   state_id           state  region_id
0         1        Kentucky          1
1         2      California          2
2         3         Florida          1
3         4  North Carolina          1
4         5      Washington          2

In [6]:
# Create a DataFrame for 'City':

df_city = pd.DataFrame(columns=["city_id", "city", "state_id"])

# INSERT DATA : CITY
unique_cities = (
    df[["City", "State"]]
    .dropna()
    .drop_duplicates()
    .merge(df_state, left_on="State", right_on="state")
    [["City", "state_id"]]
)
df_city = unique_cities.reset_index(drop=True)
df_city.insert(0, "city_id", range(1, len(df_city) + 1))
df_city = df_city.rename(columns={"City": "city"})

df_city.head(10)

   city_id             city  state_id
0        1        Henderson         1
1        2      Los Angeles         2
2        3  Fort Lauderdale         3
3        4          Concord         4
4        5          Seattle         5
5        6       Fort Worth         6
6        7          Madison         7
7        8      West Jordan         8
8        9    San Francisco         2
9       10          Fremont         9

In [7]:
# Create a DataFrame for 'Postal Code':

df_postal_code = pd.DataFrame(columns=["postal_code_id", "postal_code"])

# INSERT DATA : POSTAL CODE
unique_postcodes = df["Postal Code"].dropna().unique()
df_postal_code = pd.DataFrame({
    "postal_code_id": range(1, len(unique_postcodes) + 1),
    "postal_code":    unique_postcodes
})
 
df_postal_code.head(10)

   postal_code_id  postal_code
0               1        42420
1               2        90036
2               3        33311
3               4        90032
4               5        28027
5               6        98103
6               7        76106
7               8        53711
8               9        84084
9              10        94109

In [8]:
# Create a DataFrame for 'Postal Code - City':

df_postalcode_city = pd.DataFrame(
    columns=["postalcode_city_id", "postal_code_id", "city_id"]
)

# INSERT DATA : POSTAL CODE - CITY
pc_city_pairs = (
    df[["Postal Code", "City"]]
    .dropna()
    .drop_duplicates()
    .merge(df_postal_code, left_on="Postal Code", right_on="postal_code")
    .merge(df_city,        left_on="City",         right_on="city")
    [["postal_code_id", "city_id"]]
)
df_postalcode_city = pc_city_pairs.reset_index(drop=True)
df_postalcode_city.insert(0, "postalcode_city_id", range(1, len(df_postalcode_city) + 1))

df_postalcode_city.head(10)

   postalcode_city_id  postal_code_id  city_id
0                   1               1        1
1                   2               1      294
2                   3               2        2
3                   4               3        3
4                   5               4        2
5                   6               5        4
6                   7               5      121
7                   8               5      183
8                   9               6        5
9                  10               7        6

In [9]:
# Create a DataFrame for 'Segment':

df_segment = pd.DataFrame(columns=["segment_id", "segment"])

# INSERT DATA : SEGMENT
unique_segments = df["Segment"].dropna().unique()
df_segment = pd.DataFrame({
    "segment_id": range(1, len(unique_segments) + 1),
    "segment":    unique_segments
})

df_segment.head(10)

   segment_id      segment
0           1     Consumer
1           2    Corporate
2           3  Home Office

In [10]:
# Create a DataFrame for 'Customer':

df_customer = pd.DataFrame(
    columns=["customer_id", "customer_name", "segment_id"]
)

# INSERT DATA : CUSTOMER
unique_customers = (
    df[["Customer ID", "Customer Name", "Segment"]]
    .dropna()
    .drop_duplicates(subset=["Customer ID"])
    .merge(df_segment, left_on="Segment", right_on="segment")
    [["Customer ID", "Customer Name", "segment_id"]]
)
df_customer = unique_customers.reset_index(drop=True)
df_customer = df_customer.rename(columns={
    "Customer ID":   "customer_id",
    "Customer Name": "customer_name"
})
 
df_customer.head(10)

  customer_id       customer_name  segment_id
0    CG-12520         Claire Gute           1
1    DV-13045     Darrin Van Huff           2
2    SO-20335      Sean O'Donnell           1
3    BH-11710     Brosina Hoffman           1
4    AA-10480        Andrew Allen           1
5    IM-15070        Irene Maddox           1
6    HP-14815       Harold Pawlan           3
7    PK-19075           Pete Kriz           1
8    AG-10270     Alejandro Grove           1
9    ZD-21925  Zuschuss Donatelli           1

In [11]:
# Create a DataFrame for 'Customer - Postal Code - City':

df_customer_postalcode_city = pd.DataFrame(
    columns=["customer_postalcode_city_id", "customer_id", "postalcode_city_id"]
)

# INSERT DATA : CUSTOMER - POSTAL CODE - CITY
cust_loc = (
    df[["Customer ID", "Postal Code", "City"]]
    .dropna()
    .drop_duplicates()
    .merge(df_postalcode_city
           .merge(df_postal_code, on="postal_code_id")
           .merge(df_city,        on="city_id")[["postalcode_city_id", "postal_code", "city"]],
           left_on=["Postal Code", "City"],
           right_on=["postal_code", "city"])
    [["Customer ID", "postalcode_city_id"]]
)
df_customer_postalcode_city = cust_loc.reset_index(drop=True)
df_customer_postalcode_city.insert(
    0, "customer_postalcode_city_id",
    range(1, len(df_customer_postalcode_city) + 1)
)
df_customer_postalcode_city = df_customer_postalcode_city.rename(
    columns={"Customer ID": "customer_id"}
)

df_customer_postalcode_city.head(10)

   customer_postalcode_city_id customer_id  postalcode_city_id
0                            1    CG-12520                   1
1                            2    CG-12520                   2
2                            3    DV-13045                   3
3                            4    SO-20335                   4
4                            5    BH-11710                   5
5                            6    AA-10480                   6
6                            7    AA-10480                   7
7                            8    AA-10480                   8
8                            9    IM-15070                   9
9                           10    HP-14815                  10

In [12]:
# Create a DataFrame for 'Category':

df_category = pd.DataFrame(columns=["category_id", "category"])
  
# INSERT DATA : CATEGORY
unique_categories = df["Category"].dropna().unique()
df_category = pd.DataFrame({
    "category_id": range(1, len(unique_categories) + 1),
    "category":    unique_categories
})

df_category.head(10)

   category_id         category
0            1        Furniture
1            2  Office Supplies
2            3       Technology

In [13]:
# Create a DataFrame for 'Sub-Category':

df_sub_category = pd.DataFrame(
    columns=["sub_category_id", "sub_category", "category_id"]
)

# INSERT DATA : SUB_CATEGORY
unique_subcats = (
    df[["Sub-Category", "Category"]]
    .dropna()
    .drop_duplicates()
    .merge(df_category, left_on="Category", right_on="category")
    [["Sub-Category", "category_id"]]
)
df_sub_category = unique_subcats.reset_index(drop=True)
df_sub_category.insert(0, "sub_category_id", range(1, len(df_sub_category) + 1))
df_sub_category = df_sub_category.rename(columns={"Sub-Category": "sub_category"})

df_sub_category.head(10)

   sub_category_id sub_category  category_id
0                1    Bookcases            1
1                2       Chairs            1
2                3       Labels            2
3                4       Tables            1
4                5      Storage            2
5                6  Furnishings            1
6                7          Art            2
7                8       Phones            3
8                9      Binders            2
9               10   Appliances            2

In [14]:
# Create a DataFrame for 'Product':

df_product = pd.DataFrame(
    columns=["product_id", "product_name", "sub_category_id"]
)
  
# INSERT DATA : PRODUCT
unique_products = (
    df[["Product ID", "Product Name", "Sub-Category"]]
    .dropna()
    .drop_duplicates(subset=["Product ID"])
    .merge(df_sub_category, left_on="Sub-Category", right_on="sub_category")
    [["Product ID", "Product Name", "sub_category_id"]]
)
df_product = unique_products.reset_index(drop=True)
df_product = df_product.rename(columns={
    "Product ID":   "product_id",
    "Product Name": "product_name"
})

df_product.head(10)

,product_id,product_name,sub_category_id
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,1
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",2
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,3
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,4
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,5
5,FUR-FU-10001487,Eldon Expressions Wood and Plastic Desk Access...,6
6,OFF-AR-10002833,Newell 322,7
7,TEC-PH-10002275,Mitel 5320 IP Phone VoIP phone,8
8,OFF-BI-10003910,DXL Angle-View Binders with Locking Rings by S...,9
9,OFF-AP-10002892,Belkin F5C206VTEL 6 Outlet Surge,10

In [15]:
# Create a DataFrame for 'Ship Mode':

df_ship_mode = pd.DataFrame(columns=["ship_mode_id", "ship_mode"])
  
# INSERT DATA : SHIP_MODE
unique_ship_modes = df["Ship Mode"].dropna().unique()
df_ship_mode = pd.DataFrame({
    "ship_mode_id": range(1, len(unique_ship_modes) + 1),
    "ship_mode":    unique_ship_modes
})

df_ship_mode.head(10)

   ship_mode_id       ship_mode
0             1    Second Class
1             2  Standard Class
2             3     First Class
3             4        Same Day

In [16]:
# Create a DataFrame for 'Order':

df_order = pd.DataFrame(columns=[
    "order_id", "customer_id", "product_id", "ship_mode_id",
    "order_date", "ship_date", "sales", "quantity", "discount", "profit"
])
 
# INSERT DATA : ORDER
df_order = (
    df[["Order ID", "Customer ID", "Product ID", "Ship Mode",
         "Order Date", "Ship Date", "Sales", "Quantity", "Discount", "Profit"]]
    .dropna(subset=["Order ID"])
    .merge(df_ship_mode, left_on="Ship Mode", right_on="ship_mode")
    [["Order ID", "Customer ID", "Product ID", "ship_mode_id",
      "Order Date", "Ship Date", "Sales", "Quantity", "Discount", "Profit"]]
)
df_order = df_order.rename(columns={
    "Order ID":   "order_id",
    "Customer ID": "customer_id",
    "Product ID":  "product_id",
    "Order Date":  "order_date",
    "Ship Date":   "ship_date",
    "Sales":       "sales",
    "Quantity":    "quantity",
    "Discount":    "discount",
    "Profit":      "profit"
})
 
df_order

,order_id,customer_id,product_id,ship_mode_id,order_date,ship_date,sales,quantity,discount,profit
0,CA-2017-152156,CG-12520,FUR-BO-10001798,1,11/8/2017,11/11/2017,261.95999999999998,2,0,41.913600000000002
1,CA-2017-152156,CG-12520,FUR-CH-10000454,1,11/8/2017,11/11/2017,731.940000000000055,3,0,219.581999999999994
2,CA-2017-138688,DV-13045,OFF-LA-10000240,1,6/12/2017,6/16/2017,14.619999999999999,2,0,6.8714
3,US-2016-108966,SO-20335,FUR-TA-10000577,2,10/11/2016,10/18/2016,957.577499999999986,5,0.45,-383.031000000000006
4,US-2016-108966,SO-20335,OFF-ST-10000760,2,10/11/2016,10/18/2016,22.367999999999999,2,0.2,2.5164
...,...,...,...,...,...,...,...,...,...,...
9989,CA-2015-110422,TB-21400,FUR-FU-10001889,1,1/21/2015,1/23/2015,25.248000000000001,3,0.2,4.1028
9990,CA-2018-121258,DB-13060,FUR-FU-10000747,2,2/26/2018,3/3/2018,91.959999999999994,2,0,15.6332
9991,CA-2018-121258,DB-13060,TEC-PH-10003645,2,2/26/2018,3/3/2018,258.576000000000022,2,0.2,19.3932
9992,CA-2018-121258,DB-13060,OFF-PA-10004041,2,2/26/2018,3/3/2018,29.600000000000001,4,0,13.32
9993,CA-2018-119914,CC-12220,OFF-AP-10002684,1,5/4/2018,5/9/2018,243.159999999999997,2,0,72.947999999999993

In [17]:
display(df_ship_mode.head(5))
display(df_segment.head(5))
display(df_country.head(5))
display(df_city.head(5))
display(df_state.head(5))
display(df_region.head(5))
display(df_category.head(5))
display(df_sub_category.head(5))

display(df_customer.head(5))
display(df_product.head(5))
display(df_order.head(5))

   ship_mode_id       ship_mode
0             1    Second Class
1             2  Standard Class
2             3     First Class
3             4        Same Day

   segment_id      segment
0           1     Consumer
1           2    Corporate
2           3  Home Office

   country_id        country
0           1  United States

   city_id             city  state_id
0        1        Henderson         1
1        2      Los Angeles         2
2        3  Fort Lauderdale         3
3        4          Concord         4
4        5          Seattle         5

   state_id           state  region_id
0         1        Kentucky          1
1         2      California          2
2         3         Florida          1
3         4  North Carolina          1
4         5      Washington          2

   region_id   region  country_id
0          1    South           1
1          2     West           1
2          3  Central           1
3          4     East           1

   category_id         category
0            1        Furniture
1            2  Office Supplies
2            3       Technology

   sub_category_id sub_category  category_id
0                1    Bookcases            1
1                2       Chairs            1
2                3       Labels            2
3                4       Tables            1
4                5      Storage            2

  customer_id    customer_name  segment_id
0    CG-12520      Claire Gute           1
1    DV-13045  Darrin Van Huff           2
2    SO-20335   Sean O'Donnell           1
3    BH-11710  Brosina Hoffman           1
4    AA-10480     Andrew Allen           1

,product_id,product_name,sub_category_id
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,1
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",2
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,3
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,4
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,5

,order_id,customer_id,product_id,ship_mode_id,order_date,ship_date,sales,quantity,discount,profit
0,CA-2017-152156,CG-12520,FUR-BO-10001798,1,11/8/2017,11/11/2017,261.95999999999998,2,0,41.913600000000002
1,CA-2017-152156,CG-12520,FUR-CH-10000454,1,11/8/2017,11/11/2017,731.940000000000055,3,0,219.581999999999994
2,CA-2017-138688,DV-13045,OFF-LA-10000240,1,6/12/2017,6/16/2017,14.619999999999999,2,0,6.8714
3,US-2016-108966,SO-20335,FUR-TA-10000577,2,10/11/2016,10/18/2016,957.577499999999986,5,0.45,-383.031000000000006
4,US-2016-108966,SO-20335,OFF-ST-10000760,2,10/11/2016,10/18/2016,22.367999999999999,2,0.2,2.5164

---

---

In [17]:
# Export DataFrames to Excel files:
df_country.to_excel('country.xlsx', index=False)
df_region.to_excel('region.xlsx', index=False)
df_state.to_excel('state.xlsx', index=False)
df_city.to_excel('city.xlsx', index=False)
df_postal_code.to_excel('postal code.xlsx', index=False)
df_postalcode_city.to_excel('postalcode city.xlsx', index=False)
df_segment.to_excel('segment.xlsx', index=False)
df_customer.to_excel('customer.xlsx', index=False)
df_customer_postalcode_city.to_excel('customer postalcode city.xlsx', index=False)
df_category.to_excel('category.xlsx', index=False)
df_sub_category.to_excel('sub category.xlsx', index=False)
df_product.to_excel('product.xlsx', index=False)
df_ship_mode.to_excel('ship mode.xlsx', index=False)
df_order.to_excel('order.xlsx', index=False)

In [18]:
# Export DataFrames to Excel file:
with pd.ExcelWriter('superstore_data.xlsx') as writer:
    df_country.to_excel(writer, sheet_name='Country', index=False)
    df_region.to_excel(writer, sheet_name='Region', index=False)
    df_state.to_excel(writer, sheet_name='State', index=False)
    df_city.to_excel(writer, sheet_name='City', index=False)
    df_postal_code.to_excel(writer, sheet_name='Postal Code', index=False)
    df_postalcode_city.to_excel(writer, sheet_name='PostalCode City', index=False)
    df_segment.to_excel(writer, sheet_name='Segment', index=False)
    df_customer.to_excel(writer, sheet_name='Customer', index=False)
    df_customer_postalcode_city.to_excel(writer, sheet_name='Customer PostalCode City', index=False)
    df_category.to_excel(writer, sheet_name='Category', index=False)
    df_sub_category.to_excel(writer, sheet_name='Sub Category', index=False)
    df_product.to_excel(writer, sheet_name='Product', index=False)
    df_ship_mode.to_excel(writer, sheet_name='Ship Mode', index=False)
    df_order.to_excel(writer, sheet_name='Order', index=False)



print("Outputs generated as Excel files. Completed successfully!")

Outputs generated as Excel files. Completed successfully!

In [18]:
# Export DataFrames to CSV files:

df_country.to_csv('country.csv', index=False)
df_region.to_csv('region.csv', index=False)
df_state.to_csv('state.csv', index=False)
df_city.to_csv('city.csv', index=False)
df_postal_code.to_csv('postal code.csv', index=False)
df_postalcode_city.to_csv('postalcode city.csv', index=False)
df_segment.to_csv('segment.csv', index=False)
df_customer.to_csv('customer.csv', index=False)
df_customer_postalcode_city.to_csv('customer postalcode city.csv', index=False)
df_category.to_csv('category.csv', index=False)
df_sub_category.to_csv('sub category.csv', index=False)
df_product.to_csv('product.csv', index=False)
df_ship_mode.to_csv('ship mode.csv', index=False)
df_order.to_csv('order.csv', index=False)

print("Outputs generated as CSV files. Completed successfully!")

Outputs generated as CSV files. Completed successfully!